### ISSUE TITLE
Kafka 1.0 support?

### ISSUE THREAD

**Issue by coltfred** [Spinoco/fs2-kafka#9]
I'm still fairly new to this library, but Kafka released 1.0 this week. After doing #8 is there anything that needs to be done to support the 1.0 protocol? Is there anything to be gained? Should we at least test against it so we have something to say? Really I'm just looking for guidance here as a newcomer.

**Comment by pchlupacek** [comment]
@coltfred I believe the 1.0 will be backward compatible. You perhaps may just add this to the testcase and you will see if that works.

**Comment by AdamChlupacek** [comment]
@coltfred @pchlupacek Added testcases for kafka 0.11 and 1.0.0 in #16, they all pass with the protocol for 0.10. That seems to be enough for now. We can add first class support for 1.0.0 protocol to protocols if we  really need to, but since the test pass I dont see a reason to

**Comment by eranmiz132** [comment]
it seems that the library doesn't work with kafka 1.1.0.

i get the following exception, although i am able produce new messages with the command line script "kafka-console-producer.sh":

spinoco.fs2.kafka.failure.LeaderNotAvailable: Topic: <some-topic>, partition: 0 has no leader available
	at spinoco.fs2.kafka.KafkaClient$impl$$anonfun$publishLeaderConnection$1$$anonfun$apply$64$$anonfun$apply$65$$anonfun$spinoco$fs2$kafka$KafkaClient$impl$$anonfun$$anonfun$$anonfun$$leaderUnavailable$1$2$$anonfun$apply$72$$anonfun$17.apply(KafkaClient.scala:814)
	at spinoco.fs2.kafka.KafkaClient$impl$$anonfun$publishLeaderConnection$1$$anonfun$apply$64$$anonfun$apply$65$$anonfun$spinoco$fs2$kafka$KafkaClient$impl$$anonfun$$anonfun$$anonfun$$leaderUnavailable$1$2$$anonfun$apply$72$$anonfun$17.apply(KafkaClient.scala:814)
	at fs2.Stream$InvariantOps$$anonfun$evalMap$extension$1.apply(Stream.scala:1731)
	at fs2.Stream$InvariantOps$$anonfun$evalMap$extension$1.apply(Stream.scala:1731)
	at fs2.Segment$$anon$13$$anonfun$stage0$13$$anonfun$apply$48.apply(Segment.scala:512)
	at fs2.Segment$$anon$13$$anonfun$stage0$13$$anonfun$apply$48.apply(Segment.scala:511)
	at fs2.Segment$SingleChunk$$anonfun$stage0$1.apply$mcV$sp(Segment.scala:1008)
	at fs2.Segment$.fs2$Segment$$stepAll(Segment.scala:1744)
	at fs2.Segment$Force$.unconsChunks$extension(Segment.scala:1701)
	at fs2.Segment.foldRightLazy(Segment.scala:434)
	at fs2.Stream$InvariantOps$$anonfun$flatMap$extension$1.apply(Stream.scala:1786)
	at fs2.Stream$InvariantOps$$anonfun$flatMap$extension$1.apply(Stream.scala:1770)
	at fs2.internal.FreeC$$anonfun$flatMap$1.apply(FreeC.scala:16)
	at fs2.internal.FreeC$$anonfun$flatMap$1.apply(FreeC.scala:13)
	at fs2.internal.FreeC$$anonfun$transformWith$1.apply(FreeC.scala:24)
	at fs2.internal.FreeC$$anonfun$transformWith$1.apply(FreeC.scala:23)
	at fs2.internal.Algebra$$anonfun$fs2$internal$Algebra$$uncons$1$2$$anonfun$apply$8$$anonfun$apply$9.apply(Algebra.scala:254)
	at fs2.internal.Algebra$$anonfun$fs2$internal$Algebra$$uncons$1$2$$anonfun$apply$8$$anonfun$apply$9.apply(Algebra.scala:252)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:116)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:294)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:276)
	at cats.effect.internals.IOPlatform$$anonfun$onceOnly$1.apply(IOPlatform.scala:82)
	at cats.effect.internals.IOPlatform$$anonfun$onceOnly$1.apply(IOPlatform.scala:75)
	at cats.effect.IO$$anonfun$shift$1$$anon$8.run(IO.scala:626)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
